---
title: "About the course"
---

```{r setup, include=FALSE}
htmltools::tagList(rmarkdown::html_dependency_font_awesome())
```


This is an [R Markdown website](http://rmarkdown.rstudio.com/rmarkdown_websites.html). 
The source can be found [on GitHub <i class="fa fa-github"></i>](https://github.com/UEABIO/lecture_01.git).

The link to all the labs is here: <https://philip-leftwich.github.io/physalia-lectures-intro-stats/>


## INTRODUCTION TO STATISTICS IN R FOR BIOLOGISTS AND ECOLOGISTS

### Dates

19th-22nd September 2022

## Course Overview
This course will introduce scientists and practitioners interested in applying statistical approaches in their daily routine using R as a working environment. Participants will be introduced into the mysteries of R and R Studio while learning how to perform common statistical analyses. After a short introduction on R and its principles, the focus will be on questions that could be addressed using common statistical analyses, both for descriptive statistics and for statistical inference.

# About me

Who am I?

  * Philip Leftwich
  * <a href = "https://github.com/Philip-Leftwich"><i class="fa fa-github"> GitHub</i></a>
  * <a href = "https://twitter.com/PhilipLeftwich"><i class="fa fa-twitter"> Twitter</i></a>
  
  * <a href = "https://research-portal.uea.ac.uk/en/persons/philip-leftwich"><i class="fa fa-home"> Staff webpage</i></a>
  * <a href = "https://philip-leftwich.github.io/"><i class="fa fa-home"> Personal Website</i></a>




